//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3521
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Cryptography.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Security.Cryptography.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm mismatch.
        ///    Encryption: {0}
        ///    Decryption: {1}.
        /// </summary>
        internal static string AlgorithmMismatch {
            get {
                return ResourceManager.GetString("AlgorithmMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticated data mismatch.
        ///    Encryption ({0} bits): {1}
        ///    Decryption ({2} bits): {3}.
        /// </summary>
        internal static string AuthenticatedDataMismatch {
            get {
                return ResourceManager.GetString("AuthenticatedDataMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///  Authenticated data ({1} bits): {2}
        ///  CNG cipher mode: {3}.
        /// </summary>
        internal static string AuthenticatedSymmetricAlgorithmStateString {
            get {
                return ResourceManager.GetString("AuthenticatedSymmetricAlgorithmStateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block size mismatch.
        ///    Encryption: {0}
        ///    Decryption: {1}.
        /// </summary>
        internal static string BlockSizeMismatch {
            get {
                return ResourceManager.GetString("BlockSizeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cipher mode mismatch.
        ///    Encryption: {0}
        ///    Decryption: {1}.
        /// </summary>
        internal static string CipherModeMismatch {
            get {
                return ResourceManager.GetString("CipherModeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNG chaining mode mismatch.
        ///    Encryption: {0}
        ///    Decryption: {1}.
        /// </summary>
        internal static string CngChainingModeMismatch {
            get {
                return ResourceManager.GetString("CngChainingModeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessing the last encryption state requires using a SymmetricAlgorithmLogger.  Make sure that the SymmetricAlgorithm being used was acquired through a call to EnableLogging..
        /// </summary>
        internal static string EncryptionStateRequiresSymetricAlgorithmLogger {
            get {
                return ResourceManager.GetString("EncryptionStateRequiresSymetricAlgorithmLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback size mismatch.
        ///    Encryption: {0}
        ///    Decryption:  {1}.
        /// </summary>
        internal static string FeedbackSizeMismatch {
            get {
                return ResourceManager.GetString("FeedbackSizeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IV mismatch.
        ///    Encryption: ({0} bits): {1}
        ///    Decryption:  ({2} bits): {3}.
        /// </summary>
        internal static string IVMismatch {
            get {
                return ResourceManager.GetString("IVMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key mismatch.
        ///    Encryption ({0} bits): {1}
        ///    Decryption ({2} bits): {3}.
        /// </summary>
        internal static string KeyMismatch {
            get {
                return ResourceManager.GetString("KeyMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying an AuthenticatedSymmetricAlgorithm requires an AuthenticatedSymmetricEncryptionState..
        /// </summary>
        internal static string NeedAuthenticatedEncryptionState {
            get {
                return ResourceManager.GetString("NeedAuthenticatedEncryptionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No encryption state has been captured yet..
        /// </summary>
        internal static string NoEncryptionStateCaptured {
            get {
                return ResourceManager.GetString("NoEncryptionStateCaptured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding mode mismatch.
        ///    Encryption: {0}
        ///    Decryption: {1}.
        /// </summary>
        internal static string PaddingModeMismatch {
            get {
                return ResourceManager.GetString("PaddingModeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}[{1}].
        /// </summary>
        internal static string SymmetricAlgorithmShimString {
            get {
                return ResourceManager.GetString("SymmetricAlgorithmShimString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SymmetricAlgorithm State:
        ///  Algorithm: {0}
        ///  Cipher mode: {1}
        ///  Padding mode: {2}
        ///  Block size (bits): {3}
        ///  Feedback size (bits): {4}
        ///  Key ({5} bits): {6}
        ///  IV ({7} bits): {8}.
        /// </summary>
        internal static string SymmetricAlgorithmStateString {
            get {
                return ResourceManager.GetString("SymmetricAlgorithmStateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cryptographic object was not accessed in a thread safe manner..
        /// </summary>
        internal static string ThreadSafetyViolation {
            get {
                return ResourceManager.GetString("ThreadSafetyViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
